spring.application.name=super-admin-backend
# MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/super_admin_db
spring.datasource.username=root
spring.datasource.password=mstech
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.devtools.restart.enabled=false
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

firebase.config.path=classpath:firebase/firebase-credentials.json
firebase.project-id=boutique-staff-app

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rakeshmadasumstech@gmail.com
spring.mail.password=bskbfcfmfwohunfs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true